imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        default_connection: postgres
        connections:
            postgres:
                driver: pdo_sqlite
                path: "%kernel.cache_dir%/database.sqlite"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
