parameters:
    secret: a3d55788f213a9a00e7ba35b404df05e94a84f1b

    database_host: 192.168.99.100
    database_port: 5432
    database_name: postgres
    database_user: root
    database_password: null

    mailer_transport: smtp
    mailer_host: 192.168.99.100:1025
    mailer_user: null
    mailer_password: null
